#!/usr/bin/env bash
# ------------------------------------------------------------------
# WebTape Replayer — one-command self-host script
#
# Usage (zero config, random password auto-generated):
#   curl -fsSL https://raw.githubusercontent.com/chernbo/webTape/main/deploy/install.sh | bash
# Or download and run locally:
#   bash install.sh
#
# Environment variables (all optional):
#   WEBTAPE_DIR       install directory, default ./webtape
#   WEBTAPE_PORT      exposed port, default 3100
#   REPLAYER_IMAGE    image, default ghcr.io/chernbo/webtape-replayer:latest
#   WEBTAPE_NO_START  set to 1 to only generate .env + compose without starting (for inspection)
#
# Prerequisites:
#   - Docker + Docker Compose v2 installed
#   - REPLAYER_IMAGE is pullable (public image; for a private one, docker login first)
# ------------------------------------------------------------------
set -euo pipefail

WEBTAPE_DIR="${WEBTAPE_DIR:-webtape}"
WEBTAPE_PORT="${WEBTAPE_PORT:-3100}"
REPLAYER_IMAGE="${REPLAYER_IMAGE:-ghcr.io/chernbo/webtape-replayer:latest}"

log()  { printf '\033[36m[webtape]\033[0m %s\n' "$*"; }
die()  { printf '\033[31m[webtape] error:\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Environment checks ─────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker not found. Please install Docker first: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 (docker compose) not found. Please upgrade Docker."

# ── 2. Prepare install directory ──────────────────────────
mkdir -p "$WEBTAPE_DIR"
cd "$WEBTAPE_DIR"
log "install directory: $(pwd)"

# ── 3. Generate .env (random passwords, kept if it already exists) ──
gen_secret() {
  # prefer openssl, fall back to /dev/urandom
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${1:-16}"
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$(( ${1:-16} * 2 ))"
  fi
}

if [ -f .env ]; then
  log ".env already exists, reusing it (existing passwords are kept)"
else
  MYSQL_ROOT_PASSWORD="$(gen_secret 16)"
  MYSQL_PASSWORD="$(gen_secret 12)"
  cat > .env <<EOF
# Auto-generated by install.sh — passwords are random, keep them safe
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=fed_bugtape
MYSQL_USER=webtape
MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Public URL used in replay links (change to your public domain when sharing)
REPLAYER_PUBLIC_URL=http://localhost:${WEBTAPE_PORT}

# CORS: self-hosted without a gateway, open by default so business pages can upload cross-origin.
# In production, set an allowlist of business domains, e.g. https://a.example.com,https://b.example.com
CORS_ALLOW_ORIGIN=*

# Image and port
REPLAYER_IMAGE=${REPLAYER_IMAGE}
WEBTAPE_PORT=${WEBTAPE_PORT}
EOF
  chmod 600 .env
  log "generated .env (random passwords, mode 600)"
fi

# ── 4. Generate docker-compose.yml ────────────────────────
cat > docker-compose.yml <<'YAML'
services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD} --silent',
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  replayer:
    image: ${REPLAYER_IMAGE:-ghcr.io/chernbo/webtape-replayer:latest}
    # Image is published for amd64 only; pin the platform so arm64 hosts
    # (e.g. Apple Silicon) can still pull & run it via Rosetta/QEMU emulation.
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      REPLAYER_PUBLIC_URL: ${REPLAYER_PUBLIC_URL}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-*}
      NODE_ENV: production
    ports:
      - '${WEBTAPE_PORT:-3100}:3000'
    # Create tables from schema on start, then launch Next.js
    command: >
      sh -c "pnpm prisma db push && pnpm exec next start --hostname 0.0.0.0 --port 3000"

volumes:
  mysql-data:
YAML
log "generated docker-compose.yml"

# ── 5. Start ──────────────────────────────────────────────
if [ "${WEBTAPE_NO_START:-0}" = "1" ]; then
  log "WEBTAPE_NO_START=1, skipping start. Run later with: cd $WEBTAPE_DIR && docker compose up -d"
  exit 0
fi

log "pulling image and starting services (first run may take a while)..."
docker compose pull
docker compose up -d

log "services started ✅"
log "open: http://localhost:${WEBTAPE_PORT}"
log "logs: (cd $WEBTAPE_DIR && docker compose logs -f replayer)"
log "stop: (cd $WEBTAPE_DIR && docker compose down)"
